spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ff_portfolio_prod
    username: ff_prod_user
    password: ffprod
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
