spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ff_portfolio_dev
    username: ff_dev_user
    password: ffdev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ff_database_create.sql